[SS-04] build: add docker compose for local db set up
Indie-Creator-Community/side-project-starter-kit pull request #5
Opened 2023-05-12 20:30 UTC by ksreyr

## Changes Made 🎉

- [x] build: add docker compose for local db set up)[build: add docker compose for local db set up

### Describe Changes
 **Readme**
- updated to show how to use it

**Docker Compose**
- profiles added

**package.json**
- task to trigger the db setting up locally

**.env.template**
- updated with the docker url 

**.gitignore**
- updated to exclude IntelliJ idea IDE

## Related Issue(s)

- #4 

## Visuals (Optional)

## Checklist ✅

- [x] My code follows the code style of this project.

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-05-15 23:04 UTC, serudda requested changes

2023-05-15 23:04 UTC, serudda commented on .gitignore
> +# webstrom
```suggestion
# webstorm
```

2023-05-15 23:04 UTC, serudda commented on README.md
> +   4.1 (Optional) Generate local Database
Parece obvio, pero seria bueno indicar que es necesario instalar Docker, y que es necesario tenerlo prendido... me demore un ratito descubriendo que tenia que abrir la app para que no me diera error.

2023-05-15 23:04 UTC, serudda commented on README.md
> +      ```
```suggestion
   > It is required to modify `DATABASE_URL` variable at .env.* file to target the local database.

   If you want to shut down the database please execute the following statement
      ```
      pnpm db:docker:shutdown
      ```
```

2023-05-17 21:33 UTC, ksreyr commented on .gitignore
> +# webstrom
Seru aqui no entiendo cual seria el cambio :S

2023-05-17 21:40 UTC, ksreyr commented on README.md
> +      ```
Hecho el cambio :D

2023-05-17 21:40 UTC, ksreyr commented on README.md
> +   4.1 (Optional) Generate local Database
Hecho seru :D

2023-05-31 21:36 UTC, serudda approved these changes

2023-05-31 21:37 UTC, merged