[SS-06] dockerization
Indie-Creator-Community/side-project-starter-kit pull request #7
Opened 2023-05-12 22:00 UTC by ksreyr

## Changes Made 🎉
Implemented Docker compose and revised environment configuration

### Describe Changes

- Implemented Docker compose: The docker-compose.yml file was introduced. This allows the application and the database to be spun up together using Docker, ensuring a consistent and reproducible development environment.

- Updated the .env.example file: The structure of this file was modified to reflect changes in how environment variables are managed. Instead of .env, we are now using .env.local.

- Made adjustments to README.md: The installation instructions were updated to account for changes in the .env file and the addition of Docker. It now includes both manual installation and Docker installation instructions.

- Added node_modules and postgres_data to gitignore: These directories are typically not included in version control because they contain locally generated data.

- Modified the DATABASE_URL in the Dockerfile: This allows the application to connect to the Postgres database when running in a Docker container.

- Added new scripts in package.json for Docker and database startup and shutdown operations.

- Altered a greeting message in index.tsx to include "Hello Zyruks".

- Updated docker-compose.yml file to include app, postgres, and pgadmin services, enabling efficient local development with Docker.

## Related Issue(s)

#6 

## Checklist ✅

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-05-15 23:16 UTC, serudda requested changes

2023-05-15 23:16 UTC, serudda commented on apps/nextjs/src/pages/index.tsx
> +              Side Project Starter Kit-Hello Zyruks
```suggestion
              Side Project Starter Kit
```

2023-05-15 23:16 UTC, serudda commented on README.md
> +   It is required to modify `DATABASE_URL` variable at .env.* file to target the local database
Esto ya viene del PR #4

2023-05-15 23:16 UTC, serudda commented on README.md
> +   DATABASE_URL="postgresql://root:admin@postgres:5432/started-db?schema=public"
Esta ruta es siempre la misma? Si es asi, deberiamos ponerla por default en los .env.example

2023-05-15 23:16 UTC, serudda commented on docker-compose.yml
> +      - 3000:3000
Esto es correcto?
3000:3000 ?

2023-05-15 23:16 UTC, serudda commented on docker-compose.yml
> +      - startedProject
Que significa el started project? el nombre del repo?

2023-05-16 16:18 UTC, Zyruks commented on README.md
> +   DATABASE_URL="postgresql://root:admin@postgres:5432/started-db?schema=public"
Son dos rutas diferentes, Una es localhost:5432 para tener la base de datos local y la otra es postgres:5432 para tenerla en docker.

2023-05-17 21:09 UTC, ksreyr commented on apps/nextjs/src/pages/index.tsx
> +              Side Project Starter Kit-Hello Zyruks
perfecto Seru se me fue ese typo. ya lo cambio :D

2023-05-17 21:10 UTC, ksreyr commented on README.md
> +   It is required to modify `DATABASE_URL` variable at .env.* file to target the local database
si exacto es para no generar conflictos

2023-05-17 21:10 UTC, ksreyr commented on README.md
> +   DATABASE_URL="postgresql://root:admin@postgres:5432/started-db?schema=public"
Si Seru siempre es la misma y esta como comentario ya incluida :D

2023-05-17 21:12 UTC, ksreyr commented on docker-compose.yml
> +      - 3000:3000
si señor es el puerto con el cual pnpm normalmente se levanta. aveces cuando esta ocupado busca otros como el 3001 y 3002 y asi pero lastimosamente esa búsqueda de puertos no es posible con docker.

2023-05-17 21:13 UTC, ksreyr commented on docker-compose.yml
> +      - startedProject
aqui es un nombre que le di como para diferenciarlo de reward system pero da igual que nombre se ponga lo importante es que en los servicios del docker compose tenga el mismo nombre en la parte de networks

2023-05-17 21:45 UTC, ksreyr commented on apps/nextjs/src/pages/index.tsx
> +              Side Project Starter Kit-Hello Zyruks
hecho

2023-05-31 21:39 UTC, serudda approved these changes

2023-05-31 21:41 UTC, merged